export const addIdeaConstants = {
    IDEA_UPDATE_TITLE: "IDEA_UPDATE_TITLE",
    IDEA_UPDATE_DESCRIPTION: "IDEA_UPDATE_DESCRIPTION",
    IDEA_UPDATE_DOCUMENTS: "IDEA_UPDATE_DOCUMENTS",
    IDEA_UPDATE_IDEA_TAGS: "IDEA_UPDATE_IDEA_TAGS",
    IDEA_UPDATE_LOOKING_FOR_TEAM: "IDEA_UPDATE_LOOKING_FOR_TEAM",
    IDEA_UPDATE_LOOKING_FOR_MENTOR: "IDEA_UPDATE_LOOKING_FOR_MENTOR",
    IDEA_UPDATE_ROLE_LOOKING_FOR: "IDEA_UPDATE_ROLE_LOOKING_FOR",
    IDEA_CLEAR_DATA: "IDEA_CLEAR_DATA",
}