export const addProjectConstants = {
    PROJECT_UPDATE_TITLE: "PROJECT_UPDATE_TITLE",
    PROJECT_UPDATE_DESCRIPTION: "PROJECT_UPDATE_DESCRIPTION",
    PROJECT_UPDATE_PROJECT_TAGS: "PROJECT_UPDATE_PROJECT_TAGS",
    PROJECT_UPDATE_MENTIONS: "PROJECT_UPDATE_MENTIONS",
    PROJECT_UPDATE_TEAM_ID: "PROJECT_UPDATE_TEAM_ID",
    PROJECT_UPDATE_PROJECT_STATUS: "PROJECT_UPDATE_PROJECT_STATUS",
    PROJECT_UPDATE_LOOKING_FOR_ROLES: "PROJECT_UPDATE_LOOKING_FOR_ROLES",
    PROJECT_UPDATE_DOCUMENTS: "PROJECT_UPDATE_DOCUMENTS",
    PROJECT_CLEAR_DATA: "PROJECT_CLEAR_DATA",
    PROJECT_UPDATE_USER_ID: "PROJECT_USER_ID",
}

