export const addTeamConstants = {
    TEAM_UPDATE_TITLE: 'TEAM_UPDATE_TITLE',
    TEAM_UPDATE_LOOKING_FOR_MEMBERS: 'TEAM_UPDATE_LOOKING_FOR_MEMBERS',
    TEAM_UPDATE_LOOKING_FOR_MENTOR: 'TEAM_UPDATE_LOOKING_FOR_MENTOR',
    TEAM_UPDATE_TEAM_TAGS: 'TEAM_UPDATE_TEAM_TAGS',
    TEAM_UPDATE_ROLE: 'TEAM_UPDATE_ROLE',
    TEAM_UPDATE_MEMBERS: ' TEAM_UPDATE_MEMBERS',
    TEAM_CLEAR_DATA: 'TEAM_CLEAR_DATA',
    TEAM_UPDATE_AVATAR: 'TEAM_UPDATE_AVATAR',
}
