export const connectionActionTypes = {
    PENDING_REQUESTS: 'PENDING_REQUESTS',
    MY_CONNECTIONS: 'MY_CONNECTIONS',
    PEOPLE_YOU_MAY_KNOW: 'PEOPLE_YOU_MAY_KNOW',
    CONNECT_REQUEST_ACCEPT_PENDING: 'CONNECT_REQUEST_ACCEPT_PENDING',
}
