export const connectionActionTypes = {
    PENDING_REQUESTS: 'PENDING_REQUESTS',
    MY_CONNECTIONS: 'MY_CONNECTIONS',
    PEOPLE_YOU_MAY_KNOW: 'PEOPLE_YOU_MAY_KNOW',
    CONNECT_REQUEST_ACCEPT_PENDING: 'CONNECT_REQUEST_ACCEPT_PENDING',
    CONNECTION_DATA: 'CONNECTION_DATA',
    MY_CONNECTIONS_COMPLETE: 'MY_CONNECTIONS_COMPLETE',
    CONNECTED_ACCOUNT_ID: 'CONNECTED_ACCOUNT_ID',
}
