export const CREATE_TEAM = 'CREATE_TEAM'

export const GET_TEAMS = 'GET_TEAMS'

export const INVITE_MEMBERS ='INVITE_MEMBERS'

export const ACCEPT_JOIN_REQUEST= 'ACCEPT_JOIN_REQUEST'
export const REJECT_JOIN_REQUEST ='REJECT_JOIN_REQUEST'