export const userInfoConstants ={
    UPDATE_FIRSTNAME: "UPDATE_FIRSTNAME",
    UPDATE_LASTNAME: "UPDATE_LASTNAME",
    UPDATE_BIO: "UPDATE_BIO",
    UPDATE_AVATAR: "UPDATE_AVATAR",
    UPDATE_EMAIL_ID: "UPDATE_EMAIL_ID",
    UPDATE_ROLE: "UPDATE_ROLE",
    UPDATE_DESIGNATION: "UPDATE_DESIGNATION",
    UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
    UPDATE_ORGANIZATIONAL_ROLE: "UPDATE_ORGANIZATION_ROLE",
    UPDATE_UNIVERSITY: "UPDATE_UNIVERSITY",
    UPDATE_GRADUATION_YEAR: "UPDATE_GRADUATION_YEAR",
    UPDATE_JOURNEY_START_DATE: "UDPATE_JOURNEY_START_DATE",
    UPDATE_YEARS_OF_PROFESSIONAL_EXPERIENCE: "UPDATE_YEARS_OF_PROFESSIONAL_EXPERIENCE",
    UPDATE_DEGREE: "UPDATE_DEGREE",
    UPDATE_AOI: "UPDATE_AOI",
}

