const users = [
    {
        id: 0,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'mentor',
        organization: 'Google',
    },
    {
        id: 1,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'mentor',
        organization: 'Facebook',
    },
    {
        id: 2,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'student',
        organization: 'Microsoft',
    },
    {
        id: 3,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'student',
        organization: 'Microsoft',
    },
    {
        id: 4,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'student',
        organization: 'Microsoft',
    },
    {
        id: 5,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'student',
        organization: 'Inovact',
    },
    {
        id: 6,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'enterprenuer',
        organization: 'Inovact',
    },
    {
        id: 7,
        name: 'User' + Math.random().toString().substring(2, 4),
        avatar: 'https://bit.ly/3EKg3dQ',
        designation: 'ReactJs Developer',
        connected_at: '2021-10-12T15:52:58.312629+00:00',
        role: 'enterprenuer',
        organization: 'walmart',
    },
]

export { users }
